# Generated by Django 3.1.5 on 2021-01-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0002_remove_requests_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Requests.requests'),
        ),
    ]
