# Generated by Django 3.1.5 on 2021-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0003_requests_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
