# Generated by Django 3.1.5 on 2021-01-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0004_auto_20210118_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
