# Generated by Django 3.1.5 on 2021-01-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0005_auto_20210118_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='reply',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Requests.requests')),
            ],
        ),
    ]
