# Generated by Django 3.1.5 on 2021-01-18 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0007_reply_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='reply',
            name='wrote_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
