# Generated by Django 3.1.5 on 2021-01-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0010_requests_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
